{{- if eq .Values.vectorStore "redis-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: "vdb-redis-cluster-headless"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis-cluster
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  - name: cluster-bus
    port: 16379
    targetPort: 16379
    protocol: TCP
  {{- if index .Values "redis-cluster" "metrics" "enabled" }}
  - name: metrics
    port: 9121
    targetPort: 9121
    protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
