---
dockerfile: "Dockerfile"
docker_context: "./../../"
dependencies:
   - pip-manual
   - apt
pip-manual:
  packages:
    - optimum[habana]
    - triton
    - git/HabanaAI/vllm-fork
    - absl-py
    - accelerate
    - aiohappyeyeballs
    - aiohttp
    - aiosignal
    - airportsdata
    - annotated-doc
    - annotated-types
    - anyio
    - astor
    - async-timeout
    - atheris
    - attrs
    - autocommand
    - av
    - backports.tarfile
    - blake3
    - cachetools
    - certifi
    - charset-normalizer
    - click
    - cloudpickle
    - compressed-tensors
    - coverage
    - depyf
    - dill
    - diskcache
    - distro
    - dnspython
    - einops
    - email-validator
    - exceptiongroup
    - expecttest
    - fastapi
    - fastapi-cli
    - fastapi-cloud-cli
    - filelock
    - frozenlist
    - fsspec
    - gguf
    - googleapis-common-protos
    - grpcio
    - h11
    - habana-media-loader
    - habana-pyhlml
    - hf-xet
    - httpcore
    - httptools
    - httpx
    - huggingface-hub
    - idna
    - importlib_metadata
    - inflect
    - interegular
    - jaraco.collections
    - jaraco.context
    - jaraco.functools
    - jaraco.text
    - Jinja2
    - jiter
    - jsonschema
    - jsonschema-specifications
    - lark
    - lightning
    - lightning-habana
    - lightning-utilities
    - llguidance
    - lm-format-enforcer
    - Markdown
    - markdown-it-py
    - MarkupSafe
    - mdurl
    - mistral_common
    - more-itertools
    - mpi4py
    - mpmath
    - msgpack
    - msgspec
    - multidict
    - nest-asyncio
    - networkx
    - neural_compressor_pt
    - ninja
    - numpy
    - nvidia-ml-py
    - openai
    - opencv-python-headless
    - opentelemetry-api
    - opentelemetry-exporter-otlp
    - opentelemetry-exporter-otlp-proto-common
    - opentelemetry-exporter-otlp-proto-grpc
    - opentelemetry-exporter-otlp-proto-http
    - opentelemetry-proto
    - opentelemetry-sdk
    - opentelemetry-semantic-conventions
    - opentelemetry-semantic-conventions-ai
    - outlines
    - outlines_core
    - packaging
    - pandas
    - parameterized
    - partial-json-parser
    - perfetto
    - pillow
    - Pillow-SIMD
    - platformdirs
    - prettytable
    - prometheus-fastapi-instrumentator
    - prometheus_client
    - propcache
    - protobuf
    - psutil
    - py-cpuinfo
    - pybind11
    - pycountry
    - pydantic
    - pydantic-extra-types
    - pydantic_core
    - pydot
    - Pygments
    - pynvml
    - pyparsing
    - python-dateutil
    - python-dotenv
    - python-json-logger
    - python-multipart
    - pytorch-lightning
    - pytz
    - PyYAML
    - pyzmq
    - ray
    - referencing
    - regex
    - requests
    - rich
    - rich-toolkit
    - rignore
    - rpds-py
    - safetensors
    - scipy
    - sentencepiece
    - sentry-sdk
    - setuptools-scm
    - shellingham
    - six
    - sniffio
    - starlette
    - symengine
    - sympy
    - tabulate
    - tdqm
    - tensorboard
    - tensorboard-data-server
    - tiktoken
    - tokenizers
    - tomli
    - torch
    - torch_tb_profiler
    - torchaudio
    - torchdata
    - torchmetrics
    - torchtext
    - torchvision
    - tqdm
    - transformers
    - triton
    - typeguard
    - typer
    - typing-inspection
    - typing_extensions
    - tzdata
    - urllib3
    - uvicorn
    - uvloop
    - vllm-hpu-extension
    - watchfiles
    - wcwidth
    - websockets
    - Werkzeug
    - xgrammar
    - yarl
    - zipp
