apiVersion: v2
name: edp-redis
description: Standalone Redis 8.2.2 for EDP
type: application
version: 1.0.3
appVersion: "2.1.0"
annotations:
  app.kubernetes.io/part-of: ERAG
  dependency-only: "true"

