# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  embedding-vllm-model-server:
    image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.14.0
    container_name: embedding-vllm-model-server
    ports:
      - "${EMBEDDING_VLLM_PORT}:80"
    volumes:
      - "./data:/data"
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      VLLM_CPU_KVCACHE_SPACE: ${VLLM_CPU_KVCACHE_SPACE}
      VLLM_TARGET_DEVICE: "cpu"
    ipc: host
    command:  "--model ${EMBEDDING_VLLM_MODEL_NAME} \
              --dtype ${VLLM_DTYPE} \
              --enforce_eager \
              --download_dir /data \
              --host 0.0.0.0 --port 80"

  embedding_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/embeddings/impl/microservice/Dockerfile
    container_name: embedding-vllm-microservice
    ipc: host
    runtime: runc
    network_mode: host
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      EMBEDDING_CONNECTOR: ${EMBEDDING_CONNECTOR}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_VLLM_MODEL_NAME}
      EMBEDDING_MODEL_SERVER: vllm
      EMBEDDING_MODEL_SERVER_ENDPOINT: http://localhost:${EMBEDDING_VLLM_PORT}
    restart: unless-stopped
    depends_on:
      -   embedding-vllm-model-server

