# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-status-watcher-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: namespace-status-watcher
    app.kubernetes.io/component: status-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: namespace-status-watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: namespace-status-watcher
    spec:
      serviceAccountName: namespace-status-watcher-sa
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: namespace-status-watcher
        {{ if .Values.alternateTagging }}
        image: {{ .Values.namespaceStatusWatcher.image.repository }}:{{ .Values.namespaceStatusWatcher.image.name }}_{{ .Values.namespaceStatusWatcher.image.tag }}
        {{ else }}
        image: {{ .Values.namespaceStatusWatcher.image.repository }}/{{ .Values.namespaceStatusWatcher.image.name }}:{{ .Values.namespaceStatusWatcher.image.tag }}
        {{ end }}
        imagePullPolicy: {{ .Values.namespaceStatusWatcher.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 9010
          protocol: TCP
        env:
        - name: TARGET_NAMESPACE
          value: "{{ .Release.Namespace }}"
        livenessProbe:
          httpGet:
            path: /v1/health_check
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /v1/health_check
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.namespaceStatusWatcher.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
