# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: namespace-status-watcher-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: namespace-status-watcher
    app.kubernetes.io/component: status-monitor
spec:
  type: ClusterIP
  ports:
    - port: 9010
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: namespace-status-watcher
