---
manifest_namespace: "default"
manifest_name: "erag-deployment-manifest"

manifest_namespace_labels:
  meta.erag/is-metadata-namespace: "true"

manifest_labels:
  app.kubernetes.io/name: "erag-deployment"
  app.kubernetes.io/component: "deployment-manifest"
  app.kubernetes.io/managed-by: "ansible"

manifest_label_selector: "app.kubernetes.io/name=erag-deployment,app.kubernetes.io/component=deployment-manifest"

manifest_status_in_progress: "in-progress"
manifest_status_complete: "complete"
manifest_status_deleting: "deleting"

# Unset version value (null/empty for YAML)
manifest_unset_version: ""
