# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: traces
type: application
version: 1.0.1
appVersion: "2.0.1"
annotations:
  app.kubernetes.io/part-of: ERAG

dependencies:

#########################################################
# Tempo - traces backend
#########################################################
# enabled by default
- name: tempo
  alias: tempo
  condition: tempo.enabled
  repository: https://grafana.github.io/helm-charts
  version: 1.23.3
  tags:
  - traces
  - backend

#########################################################
# OpenTelemetry operator
#########################################################
- name: opentelemetry-operator
  version: 0.97.1
  alias: otel-operator
  condition: otel-operator.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  tags:
  - traces
  - collector
