# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: Set override_values.yaml path
  ansible.builtin.set_fact:
    keycloak_helm_override_values_path: "{{ tmp_dir }}/{{ keycloak.helm.chart_name }}-override-values.yaml"
  tags:
    - install
    - pre-upgrade

- name: Ensure Helm repository is added
  kubernetes.core.helm_repository:
    name: "{{ keycloak.helm.repo_name }}"
    repo_url: "{{ keycloak.helm.repo_url }}"
    state: present
  tags:
    - install
    - pre-upgrade

- name: Build Helm chart dependencies
  ansible.builtin.command:
    cmd: helm dependency build
    chdir: "{{ keycloak.helm.chart_directory }}"
  register: helm_dependency_build_result
  until: helm_dependency_build_result is succeeded
  retries: 5
  delay: 15
  tags:
    - install

- name: Ensure namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ keycloak.namespace }}"
  tags:
    - install
    - pre-upgrade

- name: Enforce PSS
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ keycloak.namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: "restricted"
  when: enforcePSS
  tags:
    - install

- name: Create TLS secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ keycloak.tls.secret_name }}"
        namespace: "{{ keycloak.namespace }}"
      data:
        tls.crt: "{{ lookup('file', pathToCert) | b64encode }}"
        tls.key: "{{ lookup('file', pathToKey) | b64encode }}"
      type: kubernetes.io/tls
  tags:
    - install

- name: Generate PostgreSQL password
  ansible.builtin.include_role:
    name: generate_password
    tasks_from: generate_password.yaml
  loop:
    - { name: KEYCLOAK_POSTGRESQL, user: "keycloak" }
    - { name: KEYCLOAK_POSTGRESQL_ADMIN, user: "postgres" }
  tags:
    - install

- name: Generate Keycloak admin password
  ansible.builtin.include_role:
    name: generate_password
    tasks_from: generate_password.yaml
    apply:
      tags:
        - pre-upgrade
  loop:
    - { name: KEYCLOAK_REALM_ADMIN, user: "{{ keycloak.auth.admin.username }}" }
  tags:
    - install
    - pre-upgrade

- name: Create Keycloak admin secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ keycloak.auth.admin.password_secret_name }}"
        namespace: "{{ keycloak.namespace }}"
      data:
        admin-username: "{{ keycloak.auth.admin.username | b64encode }}"
        admin-password: "{{ KEYCLOAK_REALM_ADMIN_PASSWORD | b64encode }}"
  no_log: "{{ secure_logs }}"
  tags:
    - install

- name: Create PostgreSQL secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ keycloak.postgresql.password_secret_name }}"
        namespace: "{{ keycloak.namespace }}"
      data:
        password: "{{ KEYCLOAK_POSTGRESQL_PASSWORD | b64encode }}"
        postgres-password: "{{ KEYCLOAK_POSTGRESQL_ADMIN_PASSWORD | b64encode }}"
  no_log: "{{ secure_logs }}"
  tags:
    - install

- name: Generate override values file from template
  ansible.builtin.template:
    src: "values.yaml.j2"
    dest: "{{ keycloak_helm_override_values_path }}"
    mode: '0644'
  tags:
    - install
    - pre-upgrade

- name: Update Helm dependencies for Keycloak chart
  ansible.builtin.command:
    cmd: helm dependency build {{ keycloak.helm.chart_ref }}
  tags:
    - install
    - pre-upgrade

- name: Run pre-upgrade checks
  ansible.builtin.include_role:
    name: upgrade
  vars:
    release_namespace: "{{ keycloak.namespace }}"
    release_name: "{{ keycloak.helm.release_name }}"
    release_enabled: "{{ keycloak.enabled }}"
    chart_ref: "{{ keycloak.helm.chart_ref }}"
    release_values_files: >
      {{
        [keycloak.helm.default_values_file] +
        [keycloak_helm_override_values_path]
      }}
  tags:
    - pre-upgrade

- name: Install Keycloak Helm chart
  kubernetes.core.helm:
    name: "{{ keycloak.helm.release_name }}"
    chart_ref: "{{ keycloak.helm.chart_ref }}"
    namespace: "{{ keycloak.namespace }}"
    values_files: >
      {{
        [keycloak.helm.default_values_file] +
        [keycloak_helm_override_values_path]
      }}
    state: present
    create_namespace: true
    timeout: "{{ helm_timeout }}"
    wait: true
  register: helm_install_result
  until: helm_install_result is succeeded
  retries: 5
  delay: 15
  tags:
    - install

- name: Mark secret for password management
  ansible.builtin.include_role:
    name: password_mgmt
    tasks_from: markup.yaml
    apply:
      tags:
        - install
  vars:
    - namespace: "{{ keycloak.namespace }}"
    - secret_name: "{{ keycloak.auth.admin.password_secret_name }}"
    - password_mappings:
      - { key: admin-password, variable: KEYCLOAK_REALM_ADMIN_PASSWORD, user: "{{ keycloak.auth.admin.username }}" }
  tags:
    - install

- name: Mark PostgreSQL secret for password management
  ansible.builtin.include_role:
    name: password_mgmt
    tasks_from: markup.yaml
    apply:
      tags:
        - install
  vars:
    - namespace: "{{ keycloak.namespace }}"
    - secret_name: "{{ keycloak.postgresql.password_secret_name }}"
    - password_mappings:
      - { key: password, variable: KEYCLOAK_POSTGRESQL_PASSWORD, user: "keycloak" }
      - { key: postgres-password, variable: KEYCLOAK_POSTGRESQL_ADMIN_PASSWORD, user: "postgres" }
  tags:
    - install

- name: Initial keycloak configuration
  ansible.builtin.include_tasks: configure_keycloak.yaml
  tags:
    - install

- name: Uninstall Helm chart
  kubernetes.core.helm:
    name: "{{ keycloak.helm.release_name }}"
    namespace: "{{ keycloak.namespace }}"
    state: absent
  tags:
    - uninstall

- name: Delete namespace
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ keycloak.namespace }}"
  tags:
    - uninstall
