# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
velero:
  enabled: false
  namespace: "velero"

  velero_pod_labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/name: velero

  install_server: true
  install_client: true
  client_version: "automatic"
  install_snapshot_class: true

  storage_class: ""

  restore_from: ""
  backup_details_from: "server"

  helm:
    repo_name: "velero-tanzu"
    repo_url: "https://vmware-tanzu.github.io/helm-charts/"
    repo_seaweedfs_name: "seaweedfs"
    repo_seaweedfs_url: "https://seaweedfs.github.io/seaweedfs/helm"
    chart_name: "velero"
    chart_version: "10.0.5"
    release_name: "velero"
    default_values_file: "{{ playbook_dir }}/../components/velero/values.yaml"
    chart_directory: "{{ playbook_dir }}/../components/velero"

  seaweedfs:
    persistence:
      master:
        size: "2Gi"
        volumeSizeLimitMB: 1024
      filer:
        size: "2Gi"
      volume:
        size: "500Gi"
