{{- if .Values.lateChunking.enabled -}}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: edp-late-chunking-configmap
  namespace: edp
data:
  CHUNK_SIZE: {{ .Values.lateChunking.config.chunk_size | quote }}
  CHUNK_OVERLAP: {{ .Values.lateChunking.config.chunk_overlap | quote }}
  EMBEDDING_ENDPOINT: {{ .Values.lateChunking.config.embedding_service_endpoint | quote }}
  EMBEDDING_MODEL_NAME: {{ .Values.lateChunking.config.model_name | quote }}
{{- end }}
