{{- if .Values.lateChunking.enabled -}}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lateChunking.nameOverride | default (include "helm-edp.fullname" .) }}
  labels:
    {{- include "helm-edp.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.lateChunking.replicas }}
  selector:
    matchLabels:
      {{- include "helm-edp.lateChunking.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "manifest.podLabels" (list .Values.lateChunking.nameOverride .) | nindent 6 }}
      {{- include "manifest.tdx.annotations" (list .Values.lateChunking.nameOverride .) | nindent 6 }}
    spec:
      {{- include "manifest.tdx.runtimeClassName" (list .Values.lateChunking.nameOverride .) | nindent 6 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-edp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-embedding-service
          image: alpine/curl
          imagePullPolicy: {{ .Values.lateChunking.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: EMBEDDING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: edp-late-chunking-configmap
                  key: EMBEDDING_ENDPOINT
          command:
            - sh
            - -c
            - |
                if [ -z "$EMBEDDING_ENDPOINT" ]; then
                  echo "Environment variable EMBEDDING_ENDPOINT is not set. Skipping the init container.";
                else
                  until curl -s $EMBEDDING_ENDPOINT; do
                    echo "waiting for embedding service $EMBEDDING_ENDPOINT to be ready...";
                    sleep 2;
                  done;
                fi;
      containers:
        - name: {{ .Values.lateChunking.nameOverride }}
          securityContext:
            {{- toYaml .Values.securityContextWithTemp | nindent 12 }}
          {{ if .Values.alternateTagging }}
          image: {{ .Values.lateChunking.repository }}:{{ .Values.lateChunking.name }}_{{ .Values.lateChunking.tag | default .Chart.AppVersion }}
          {{ else }}
          image: {{ .Values.lateChunking.repository }}/{{ .Values.lateChunking.name }}:{{ .Values.lateChunking.tag | default .Chart.AppVersion }}
          {{ end }}
          imagePullPolicy: {{ .Values.lateChunking.pullPolicy }}
          env:
          {{- if .Values.proxy.httpProxy }}
            - name: http_proxy
              value: {{ .Values.proxy.httpProxy }}
          {{- end }}
          {{- if .Values.proxy.httpsProxy }}
            - name: https_proxy
              value: {{ .Values.proxy.httpsProxy }}
          {{- end }}
          {{- if .Values.proxy.noProxy }}
            - name: no_proxy
              value: {{ include "helm-edp.noProxyWithContainers" . | quote }}
          {{- end }}
          {{- if .Values.lateChunking.environment }}
            {{- toYaml .Values.lateChunking.environment | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: vector-database-config
            - configMapRef:
                name: edp-late-chunking-configmap
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: v1/health_check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: v1/health_check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: v1/health_check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60
          resources:
            {{- $defaultValues := toYaml .Values.lateChunking.resources | nindent 12 -}}
            {{- include "manifest.getResource" (list .Values.lateChunking.nameOverride $defaultValues .Values) | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
