# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: audio-vllm-configmap
  namespace: audio
data:
  ASR_VLLM_MODEL_NAME: {{ .Values.vllmAudioCpu.config.modelName | quote }}
  VLLM_CPU_KVCACHE_SPACE: {{ .Values.vllmAudioCpu.config.cpuKvcacheSpace | quote }}
  VLLM_DTYPE: {{ .Values.vllmAudioCpu.config.dtype | quote }}
  VLLM_MAX_NUM_SEQS: {{ .Values.vllmAudioCpu.config.maxNumSeqs | quote }}
  VLLM_SKIP_WARMUP: {{ .Values.vllmAudioCpu.config.skipWarmup | quote }}
  VLLM_TP_SIZE: {{ .Values.vllmAudioCpu.config.tpSize | quote }}
  VLLM_PP_SIZE: {{ .Values.vllmAudioCpu.config.ppSize | quote }}
  VLLM_MAX_MODEL_LEN: {{ .Values.vllmAudioCpu.config.maxModelLen | quote }}
