# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.vllmAudioCpu.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "audio.vllmAudioCpu.fullname" . }}
  labels:
    {{- include "audio.vllmAudioCpu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vllmAudioCpu.service.type }}
  ports:
    - port: {{ .Values.vllmAudioCpu.service.port }}
      targetPort: {{ .Values.vllmAudioCpu.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "audio.vllmAudioCpu.selectorLabels" . | nindent 4 }}
{{- end }}
