{{- if index .Values "app-monitors" "enabled" }}
# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edp-late-chunking-svc
  labels:
    release: {{.Release.Name}}
spec:
  namespaceSelector:
    matchNames:
    - edp
  selector:
    matchLabels:
      app.kubernetes.io/instance: edp
      app.kubernetes.io/name: edp-late-chunking
  endpoints:
  - port: "http"
{{- end }}
