{{- if index .Values "app-monitors" "enabled" }}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: text-extractor-svc
  labels:
    release: {{.Release.Name}}
spec:
  namespaceSelector:
    matchNames:
    - docsum
  selector:
    matchLabels:
      app.kubernetes.io/instance: text-extractor-usvc
  endpoints:
  - port: "text-extractor"
{{- end }}
