{{- if index .Values "app-monitors" "enabled" }}
# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-embedding-svc
  labels:
    release: {{ $.Release.Name }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace | default "chatqa" }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: vllm_embedding
  endpoints:
  - port: "vllm-embedding"
{{- end }}
