# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
ingress:
  enabled: false
  namespace: "ingress-nginx"
  service_type: "NodePort"
  helm:
    repo_name: "ingress-nginx"
    repo_url: "https://kubernetes.github.io/ingress-nginx"
    chart_name: "erag-ingress-nginx"
    chart_directory: "{{ playbook_dir }}/../components/ingress"
    release_name: "ingress-nginx"
    default_values_file: "{{ playbook_dir }}/../components/ingress/values.yaml"
