# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: Set override_values.yaml path
  ansible.builtin.set_fact:
    rag_utils_helm_override_values_path: >-
      {{ tmp_dir }}/{{ rag_utils.helm.release_name }}-override-values.yaml
  tags:
    - install

- name: Generate override values file from template
  ansible.builtin.template:
    src: "values.yaml.j2"
    dest: "{{ rag_utils_helm_override_values_path }}"
    mode: '0644'
  tags:
    - install

- name: Set values_files list
  ansible.builtin.set_fact:
    values_files: >
      {{
        [rag_utils.helm.default_values_file] +
        [rag_utils_helm_override_values_path]
      }}
  tags:
    - install

- name: Install or Upgrade Helm chart
  kubernetes.core.helm:
    name: "{{ rag_utils.helm.release_name }}"
    chart_ref: "{{ rag_utils.helm.chart_directory }}"
    namespace: "{{ rag_utils.namespace }}"
    values_files: "{{ values_files }}"
    state: present
    create_namespace: false  # Must use default namespace
    timeout: "{{ helm_timeout }}"
  register: helm_repo_install_result
  until: helm_repo_install_result is succeeded
  retries: 5
  delay: 15
  tags:
    - install

- name: Uninstall Helm chart
  kubernetes.core.helm:
    name: "{{ rag_utils.helm.release_name }}"
    namespace: "{{ rag_utils.namespace }}"
    state: absent
  tags:
    - uninstall
