# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
httpProxy: ""
httpsProxy: ""
noProxy: ""
docker_version: "26.1.4"
helm_version: "v3.17.1"
kubectl_version: "v1.33.0" # since we support 1.29-1.33
insecure_registry: ""
