# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

nri:
  runtime:
    patchConfig: true

config:
  balloonTypes:
    - name: reserved
      namespaces:
        - '*'
      shareIdleCPUsInSame: system
      reservedResources:
        cpu: "1"
      pinCPU: true
      pinMemory: true
