# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.tts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: audio-tts-config
  labels:
    {{- include "audio.tts.labels" . | nindent 4 }}
data:
  TTS_MODEL_SERVER: "fastapi"
  TTS_MODEL_SERVER_ENDPOINT: "http://{{ .Values.ttsFastapiModelServer.nameOverride }}.{{ .Release.Namespace }}.svc:{{ .Values.ttsFastapiModelServer.service.port }}"
{{- end }}
