# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.tts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audio.tts.fullname" . }}
  labels:
    {{- include "audio.tts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tts.replicaCount }}
  selector:
    matchLabels:
      {{- include "audio.tts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "audio.tts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      serviceAccountName: {{ include "audio.tts.name" . }}
      initContainers:
        - name: wait-for-tts-model-server
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: alpine/curl
          imagePullPolicy: {{ .Values.tts.image.pullPolicy }}
          env:
            - name: TTS_MODEL_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: audio-tts-config
                  key: TTS_MODEL_SERVER_ENDPOINT
          command:
            - sh
            - -c
            - |
                if [ -z "$TTS_MODEL_SERVER_ENDPOINT" ]; then
                  echo "Environment variable TTS_MODEL_SERVER_ENDPOINT is not set. Skipping the init container.";
                else
                  until curl -s ${TTS_MODEL_SERVER_ENDPOINT}/health; do
                    echo "waiting for TTS model server ${TTS_MODEL_SERVER_ENDPOINT}/health to be ready...";
                    sleep 2;
                  done;
                fi;
      containers:
        - name: {{ include "audio.tts.fullname" . }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{ if .Values.alternateTagging }}
          image: {{ .Values.tts.image.repository }}:{{ .Values.tts.image.name }}_{{ .Values.tts.image.tag }}
          {{ else }}
          image: {{ .Values.tts.image.repository }}/{{ .Values.tts.image.name }}:{{ .Values.tts.image.tag }}
          {{ end }}
          imagePullPolicy: {{ .Values.tts.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: audio-tts-config
          env:
            - name: LOGFLAG
              value: "True"
          {{- if .Values.proxy.httpProxy }}
            - name: http_proxy
              value: {{ .Values.proxy.httpProxy }}
          {{- end }}
          {{- if .Values.proxy.httpsProxy }}
            - name: https_proxy
              value: {{ .Values.proxy.httpsProxy }}
          {{- end }}
          {{- if .Values.proxy.noProxy }}
            - name: no_proxy
              value: {{ .Values.proxy.noProxy }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9009
          livenessProbe:
            httpGet:
              path: /v1/health_check
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/health_check
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.tts.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
