# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.asr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "audio.asr.fullname" . }}
  labels:
    {{- include "audio.asr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.asr.service.port }}
      targetPort: {{ .Values.asr.service.targetPort }}
      protocol: TCP
      name: {{ .Values.asr.service.name }}
  selector:
    {{- include "audio.asr.selectorLabels" . | nindent 4 }}
{{- end }}
