# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
balloons:
  enabled: false
  namespace: "kube-system"
  wait_timeout: 300
  throughput_mode: true
  max_replicas_per_node: 10
  helm:
    repo_url: "https://containers.github.io/nri-plugins"
    repo_name: "nri-plugins"
    chart_name: "nri-resource-policy-balloons"
    release_name: "nri-balloons"
    chart_version: "v0.10.1"
    default_values_file: >-
      {{ playbook_dir }}/../components/nri-plugin/values.yaml
    reset_values_file: >-
      {{ playbook_dir }}/../components/nri-plugin/reset-values.yaml
    reset_balloon_file: >-
      {{ playbook_dir }}/../components/nri-plugin/reset-balloon.yaml

  controller:
    initContainer:
      name: "wait-for-balloons"
    namespace: "nri-balloons-controller"
