{{- if index .Values "pgvector" "enabled" -}}
# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/instance: pgvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgvector
      app.kubernetes.io/instance: pgvector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgvector
        app.kubernetes.io/instance: pgvector
    spec:
      serviceAccountName: default
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: pgvector
          {{- if .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.securityContextWithTemp | nindent 12 }}
          {{- end }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: POSTGRES_DB
          image: "{{ .Values.pgvector.image.repository }}:{{ .Values.pgvector.image.tag }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            {{- if index .Values "pgvector" "persistence" "enabled" }}
            - mountPath: /var/lib/postgresql
              name: pgdata
            {{- end }}
          resources:
            {{- if .Values.pgvector.resources }}
            {{- toYaml .Values.pgvector.resources | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if index .Values "pgvector" "persistence" "enabled" }}
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgvector-data
        {{- end }}
{{- end }}
