# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.ttsFastapiModelServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: audio-tts-fastapi-configmap
  labels:
    {{- include "audio.ttsFastapiModelServer.labels" . | nindent 4 }}
data:
  TTS_MODEL_NAME: {{ .Values.ttsFastapiModelServer.config.modelName | quote }}
{{- end }}
