{{- if not .Values.hierarchicalDataprep.enabled -}}
# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: edp-text-splitter-configmap
  namespace: edp
data:
  CHUNK_SIZE: {{ .Values.textSplitter.config.chunk_size | quote }}
  CHUNK_OVERLAP: {{ .Values.textSplitter.config.chunk_overlap | quote }}
  LATE_CHUNK_SIZE: {{ .Values.textSplitter.config.late_chunk_size | quote }}
  LATE_CHUNK_OVERLAP: {{ .Values.textSplitter.config.late_chunk_overlap | quote }}
  EMBEDDING_SERVICE_ENDPOINT: {{ .Values.textSplitter.config.embedding_service_endpoint | quote }}
  USE_SEMANTIC_CHUNKING: {{ .Values.textSplitter.config.use_semantic_chunking | quote }}
  USE_LATE_CHUNKING: {{ .Values.textSplitter.config.use_late_chunking | quote }}
{{- end }}
