# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
chat_history:
  enabled: false
  namespace: "chat-history"
  helm:
    version: "v3.16.1"
    release_name: "chat-history"
    chart_directory: "{{ playbook_dir }}/../components/chat_history"
    default_values_file: >-
      {{ playbook_dir }}/../components/chat_history/values.yaml
    tdx_resources_file: >-
      {{ playbook_dir }}/../components/chat_history/resources-tdx.yaml

  # FerretDB/PostgreSQL authentication settings
  database:
    auth:
      db_name: "CHAT_HISTORY"
      password_secret_name: "mongo-database-secret"
      user:
        db_user: "chat_history"
        password_file_name: "chat-history-postgres-password"
