# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
fingerprint:
  enabled: false
  namespace: "fingerprint"
  helm:
    version: "v3.16.1"
    chart_version: "1.1.0"
    release_name: "fingerprint"
    chart_directory: "{{ playbook_dir }}/../components/fingerprint"
    default_values_file: >-
      {{ playbook_dir }}/../components/fingerprint/values.yaml
    tdx_resources_file: >-
      {{ playbook_dir }}/../components/fingerprint/resources-tdx.yaml

  # FerretDB/PostgreSQL authentication settings
  database:
    auth:
      db_name: "SYSTEM_FINGERPRINT"
      password_secret_name: "mongo-database-secret"
      user:
        db_user: "fingerprint"
        password_file_name: "fingerprint-postgres-password"
