# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: traces-instr
type: application
version: 1.0.0
appVersion: "2.0.0"
annotations:
  app.kubernetes.io/part-of: ERAG
