{{ if index .Values "prometheus-mssql-exporter" "enabled"  }}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mssql-exporter
  labels:
    release: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mssql-metrics  
  namespaceSelector:
    matchNames:
      - vdb
  endpoints:
    - port: "metrics"
      path: /metrics
      interval: 30s
{{ end }}
