# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
# mitigation due to not being able to set multiple facts if they reference eachother in one task
- name: Ensure pipelines and gmc variables are defined
  ansible.builtin.set_fact:
    pipelines: "{{ pipelines | default([]) }}"
    gmc: "{{ gmc | default({}) | combine({'namespace': 'system'}, recursive=True) if gmc is defined else {'namespace': 'system'} }}"
  tags:
    - install
    - uninstall
    - restore

- name: Get list of pipelines namespaces
  ansible.builtin.set_fact:
    pipeline_namespaces: "{{ pipelines | map(attribute='namespace') | list + [gmc.namespace] }}"
  tags:
    - install
    - uninstall
    - restore

- name: Get list of component namespaces
  ansible.builtin.set_fact:
    enabled_namespaces: >
      {{
        [
          ingress.namespace if ingress.enabled else None,
          keycloak.namespace if keycloak.enabled else None,
          apisix.namespace if apisix.enabled else None,
          telemetry.monitoring.namespace if telemetry.enabled else None,
          telemetry.traces.namespace if (telemetry.enabled and telemetry.traces.enabled) else None,
          ui.namespace if ui.enabled else None,
          edp.namespace if edp.enabled else None,
          fingerprint.namespace if fingerprint.enabled else None,
          chat_history.namespace if chat_history.enabled else None,
          vector_databases.namespace if vector_databases.enabled else None,
          edp.seaweedfs.namespace if (edp.enabled and edp.storageType == 'seaweedfs') else None,
          audio.namespace if audio.enabled else None
        ]
        | select('defined') | select('truthy') | list
        +
        pipeline_namespaces
      }}
  tags:
    - install
    - uninstall
    - restore
